### ISSUE TITLE
WireMock properties that should be added by WireMock Micronaut are not available in the Micronaut environment

### ISSUE THREAD

**Issue by radu-mihail** [Nahuel92/wiremock-micronaut#37]
**Issue description**

When configuring **WireMock Micronaut** with
```java
@MicronautTest
@ConfigureWireMock(..., properties = "my.property")
class Issue {
  @Property(name = "my.property")
  String myProperty;

  // Running this test will fail dependency injection due to Micronaut not finding my.property.
  @Test
  void test() { }
}
```

in a `@MicronautTest` **JUnit 5** unit test, the `my.property` property is not available to be injected from the **Micronaut** environment.

**To reproduce**

I've reproduced this in a minimal **Micronaut** library project here: https://github.com/radu-mihail/micronaut-wiremock-properties-not-injected. Please disregard the commit mess.

```shell
git clone https://github.com/radu-mihail/micronaut-wiremock-properties-not-injected.git issue
cd issue
./gradlew clean test
```

**Expected behaviour**

`my.property` is available for Micronaut dependency injection and can be accessed via the **Micronaut** expression language.
For example:

```java
@Property(name = "my.property")
String myProperty;
...
@Inject
@Client("${my.property")
HttpClient httpClient;
...
}
```

**Actual behaviour**

**Micronaut** fails to start due to missing property for dependency injection:

```text
Failed to inject value for field [myProperty] of class: org.example.MicronautWiremockIssuesTest

Message: Failed to inject value for field [myProperty] of class: org.example.MicronautWiremockIssuesTest

Message: Error resolving property value [my.property]. Property doesn't exist
Path Taken: MicronautWiremockIssuesTest.myProperty
Path Taken: MicronautWiremockIssuesTest.myProperty
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [myProperty] of class: org.example.MicronautWiremockIssuesTest

Message: Failed to inject value for field [myProperty] of class: org.example.MicronautWiremockIssuesTest

Message: Error resolving property value [my.property]. Property doesn't exist
Path Taken: MicronautWiremockIssuesTest.myProperty
Path Taken: MicronautWiremockIssuesTest.myProperty
	at io.micronaut.context.exceptions.DependencyInjectionException.missingProperty(DependencyInjectionException.java:289)
	at io.micronaut.context.AbstractInitializableBeanDefinition.lambda$resolveValue$7(AbstractInitializableBeanDefinition.java:2093)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveValue(AbstractInitializableBeanDefinition.java:2093)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getValueForField(AbstractInitializableBeanDefinition.java:1725)
	at org.example.$MicronautWiremockIssuesTest$Definition.inject(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doInjectAndInitialize(DefaultBeanContext.java:2661)
	at io.micronaut.context.DefaultBeanContext.inject(DefaultBeanContext.java:1009)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeEach(AbstractMicronautExtension.java:459)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeEach(MicronautJunit5Extension.java:223)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Environment**

I've consistently reproduced this on:
  * **macOS 15.1.1**
  * OpenJDK Runtime Environment Zulu21.34+19-CA (build 21.0.3+9-LTS)
  * Gradle 8.11
  * Micronaut 4.7.1

**Additional context**

I've created the minimal example with **Micronaut Launch**.

Weirdly enough, if I clone the **WireMock Micronaut** repository, and run the examples, **it works**! I've been spending the past 2 days on this, and can't figure it out for the life of me.

**Comment by Nahuel92** [comment]
Hi @radu-mihail, thanks for reporting this issue. I'll take a look as soon as I have some free time to work on this.

**Comment by Nahuel92** [comment]
Hi @radu-mihail!

Your test is fine and the bug lies on my extension. I never realized that the way I implemented it is causing duplicated jUnit callbacks (beforeAll, beforeEach, etc.) calls, once for `@MicronautTest`, and once again for `@EnableWireMock`. This is messing up with the `ApplicationContext` configuration.

It may take me some time, but I'll release a fixed version. Thanks for reporting!

**Comment by radu-mihail** [comment]
Fantastic! Thank you so much for troubleshooting it so quickly, and for developing this project!

**Comment by Nahuel92** [comment]
Hi radu-mihail!

I released a new major version that should fix your issue. Please keep in mind that it has a couple of breaking changes, and you'll need to migrate your existing tests to make them work again:

Please see #38 details on how to do the migration. Hopefully it's not that much effort.

If this works for you, please go ahead and close the issue. Thanks!

**Comment by radu-mihail** [comment]
I upgraded to `2.0.0` and I confirm that the new approach works flawlessly.

The only minor downside is that one has to use a new annotation `@MicronautWireMockTest` instead of the “traditional” `@MicronautTest`, but this is just nitpicking.

Thank you so much for your work!

**Comment by Nahuel92** [comment]
> I upgraded to `2.0.0` and I confirm that the new approach works flawlessly.
> 
> The only minor downside is that one has to use a new annotation `@MicronautWireMockTest` instead of the “traditional” `@MicronautTest`, but this is just nitpicking.
> 
> Thank you so much for your work!

Thanks for sharing. Yeah, I understand that. I'll reach out to the Micronaut team to see if they somehow can expose the `ApplicationContext` so that it can be grabbed from other extensions like mine. If that can be possible, then in the future I'll switch back to the previous approach.
